/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#7d3d00',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'tertiary-container': '#a15100',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffe0cd',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-tint': '#732ee4',
        surface: '#fef7ff',
        'surface-dim': '#dfd7e6',
        'surface-bright': '#fef7ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f9f1ff',
        'surface-container': '#f3ebfa',
        'surface-container-high': '#ede5f4',
        'surface-container-highest': '#e8dfee',
        'on-surface': '#1d1a24',
        'on-surface-variant': '#4a4455',
        'inverse-surface': '#332f39',
        'inverse-on-surface': '#f6eefc',
        background: '#fef7ff',
        'on-background': '#1d1a24',
        'surface-variant': '#e8dfee',
        outline: '#7b7487',
        'outline-variant': '#ccc3d8',
        primary: '#630ed4',
        'on-primary': '#ffffff',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#d2bbff',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'on-secondary-container': '#656464',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '32px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '160px',
        'section-gap-compact': '96px',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Inter', 'sans-serif'],
        displayMobile: ['var(--font-display)', 'Inter', 'sans-serif'],
        headline: ['var(--font-headline)', 'Inter', 'sans-serif'],
        body: ['var(--font-body)', 'Inter', 'sans-serif'],
        label: ['var(--font-body)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.7', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
